import { open, mkdir, stat, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Development/test storage (no Vercel Blob token): files under
 * `<uploadsDir>/<key>`, served by app.js's /uploads static mount at
 * `/uploads/<key>`. Keys are always `community/<userId>/<uuid>.<ext>`,
 * generated by the server -- never a client filename.
 *
 * @param {{ uploadsDir: string, publicPrefix?: string }} options
 * @returns {import('../../application/ports/MediaStorage.js').MediaStorage}
 */
export function createLocalDiskMediaStorage({ uploadsDir, publicPrefix = '/uploads' }) {
  const fileFor = (url) => {
    if (typeof url !== 'string' || !url.startsWith(`${publicPrefix}/community/`)) return null;
    const rel = url.slice(publicPrefix.length + 1);
    if (rel.includes('..')) return null;
    return path.join(uploadsDir, ...rel.split('/'));
  };

  return {
    get mode() {
      return 'local';
    },

    async save(key, buffer) {
      const file = path.join(uploadsDir, ...key.split('/'));
      await mkdir(path.dirname(file), { recursive: true });
      await writeFile(file, buffer);
      return `${publicPrefix}/${key}`;
    },

    ownsUrl(url, userId) {
      return (
        typeof url === 'string' &&
        url.startsWith(`${publicPrefix}/community/${userId}/`) &&
        !url.includes('..')
      );
    },

    async inspect(url, bytes) {
      const file = fileFor(url);
      if (!file) return null;
      try {
        const { size } = await stat(file);
        const handle = await open(file, 'r');
        try {
          const head = Buffer.alloc(Math.min(bytes, size));
          await handle.read(head, 0, head.length, 0);
          return { sizeBytes: size, head };
        } finally {
          await handle.close();
        }
      } catch {
        return null;
      }
    },

    async deleteMany(urls) {
      await Promise.all(
        urls.map(async (url) => {
          const file = fileFor(url);
          if (file) await unlink(file).catch(() => {});
        }),
      );
    },
  };
}
