export const GOAL_METRIC_TYPE = Object.freeze({
  SKILL_RATING: 'SKILL_RATING',
  MATCH_WINS: 'MATCH_WINS',
  RANKING_POSITION: 'RANKING_POSITION',
  TRAINING_FREQUENCY: 'TRAINING_FREQUENCY',
  CUSTOM: 'CUSTOM',
});

export const GOAL_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  ACHIEVED: 'ACHIEVED',
  ABANDONED: 'ABANDONED',
});
