export const NOTIFICATION_TYPE = Object.freeze({
  CHALLENGE_RECEIVED: 'CHALLENGE_RECEIVED',
  CHALLENGE_ACCEPTED: 'CHALLENGE_ACCEPTED',
  CHALLENGE_REJECTED: 'CHALLENGE_REJECTED',
  CHALLENGE_CANCELLED: 'CHALLENGE_CANCELLED',
  CHALLENGE_RESULT_SUBMITTED: 'CHALLENGE_RESULT_SUBMITTED',
  CHALLENGE_RESULT_MISMATCH: 'CHALLENGE_RESULT_MISMATCH',
  CHALLENGE_RESULT_CONFIRMED: 'CHALLENGE_RESULT_CONFIRMED',
  POST_COMMENT_RECEIVED: 'POST_COMMENT_RECEIVED',
});
