import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';

import { billingClient } from '../../api/billingClient.js';
import { ToastProvider } from '../../components/ui/Toast.jsx';

import { PlansPage } from './PlansPage.jsx';

vi.mock('../../api/billingClient.js', () => ({
  billingClient: {
    listPlans: vi.fn(),
    createPlan: vi.fn(),
    updatePlan: vi.fn(),
    setPlanActive: vi.fn(),
    listPlanPrices: vi.fn(),
    setPlanPrice: vi.fn(),
    cancelScheduledPrice: vi.fn(),
    getPriceNoticeDays: vi.fn(),
    setPriceNoticeDays: vi.fn(),
  },
}));

// The medium date format differs between ICU builds ("26 de oct de 2026" / "26/10/2026").
const OCT_26 = String.raw`(?:26 de oct\.? de 2026|26\/10\/2026)`;

const INICIACION = {
  id: 'plan-1',
  code: 'INICIACION',
  name: 'Iniciación',
  description: null,
  isActive: true,
  currentPriceCop: 180000,
  scheduledPrice: null,
  activePlayers: 12,
  earliestPriceStart: '2026-10-26T00:00:00.000Z',
  noticeDays: 30,
};
const AVANZADO = {
  id: 'plan-2',
  code: 'AVANZADO',
  name: 'Avanzado',
  description: 'Competencia',
  isActive: false,
  currentPriceCop: null,
  scheduledPrice: null,
  activePlayers: 0,
  earliestPriceStart: '2026-09-26T00:00:00.000Z',
  noticeDays: 30,
};

function renderPage() {
  return render(
    <ToastProvider>
      <PlansPage />
    </ToastProvider>,
  );
}

async function openEditor(user, planName) {
  const row = (await screen.findByText(planName)).closest('li');
  await user.click(within(row).getByRole('button', { name: 'Editar plan' }));
  return screen.findByRole('dialog', { name: `Editar ${planName}` });
}

beforeEach(() => {
  vi.clearAllMocks();
  billingClient.listPlans.mockResolvedValue({ plans: [INICIACION, AVANZADO] });
  billingClient.getPriceNoticeDays.mockResolvedValue({ days: 30 });
  billingClient.listPlanPrices.mockResolvedValue({
    prices: [
      {
        id: 'pr-2',
        basePriceCop: 180000,
        previousPriceCop: 150000,
        validFrom: '2026-01-01',
        validTo: null,
        createdAt: '2025-12-01T15:00:00.000Z',
        changedByName: 'Marta Gómez',
        state: 'CURRENT',
      },
      {
        id: 'pr-1',
        basePriceCop: 150000,
        previousPriceCop: null,
        validFrom: '2025-01-01',
        validTo: '2026-01-01',
        createdAt: '2024-12-01T15:00:00.000Z',
        changedByName: 'Marta Gómez',
        state: 'PAST',
      },
    ],
  });
});

describe('PlansPage (Planes de membresía)', () => {
  it('lists plans with price, players and state; the notice setting is shown', async () => {
    renderPage();
    expect(await screen.findByText('Precio: $ 180.000')).toBeInTheDocument();
    expect(screen.getByText(/Código INICIACION · 12 jugadores/)).toBeInTheDocument();
    expect(screen.getByText('Desactivado')).toBeInTheDocument();
    expect(await screen.findByText('30 días')).toBeInTheDocument();
  });

  it('creates a plan with only a name: the code is generated by the server', async () => {
    billingClient.createPlan.mockResolvedValue({ id: 'plan-3', name: 'Competencia' });
    const user = userEvent.setup();
    renderPage();
    await user.click(await screen.findByRole('button', { name: 'Nuevo plan' }));
    const panel = await screen.findByRole('dialog', { name: 'Nuevo plan' });
    expect(within(panel).queryByLabelText(/Código/)).not.toBeInTheDocument();
    await user.type(within(panel).getByLabelText(/Nombre del plan/), 'Competencia');
    await user.click(within(panel).getByRole('button', { name: 'Crear plan' }));
    await waitFor(() =>
      expect(billingClient.createPlan).toHaveBeenCalledWith({
        name: 'Competencia',
        description: undefined,
      }),
    );
  });

  it('edits name and description; the code is shown but not editable', async () => {
    billingClient.updatePlan.mockResolvedValue({ ...INICIACION, name: 'Iniciación adultos' });
    const user = userEvent.setup();
    renderPage();
    const panel = await openEditor(user, 'Iniciación');
    expect(within(panel).getByText('INICIACION')).toBeInTheDocument();
    const name = within(panel).getByLabelText('Nombre del plan');
    await user.clear(name);
    await user.type(name, 'Iniciación adultos');
    await user.click(within(panel).getByRole('button', { name: 'Guardar cambios' }));
    await waitFor(() =>
      expect(billingClient.updatePlan).toHaveBeenCalledWith('plan-1', {
        name: 'Iniciación adultos',
        description: null,
      }),
    );
  });

  it('warns how many players will be told and starts the price after the notice', async () => {
    billingClient.setPlanPrice.mockResolvedValue({ basePriceCop: 200000, notifiedPlayers: 12 });
    const user = userEvent.setup();
    renderPage();
    const panel = await openEditor(user, 'Iniciación');

    expect(within(panel).getByText('12 jugadores tienen este plan.')).toBeInTheDocument();
    expect(
      within(panel).getByText(new RegExp(String.raw`desde el ${OCT_26} \(30 días de aviso\)`)),
    ).toBeInTheDocument();
    expect(within(panel).getByText('Las facturas ya emitidas no cambian.')).toBeInTheDocument();
    expect(within(panel).getByLabelText('Aplica desde')).toHaveValue('2026-10-26');

    // History: previous -> new, state and who changed it.
    expect(await within(panel).findByText('$ 150.000 → $ 180.000')).toBeInTheDocument();
    expect(within(panel).getByText('Vigente')).toBeInTheDocument();
    expect(within(panel).getAllByText(/por Marta Gómez/)).toHaveLength(2);

    await user.type(within(panel).getByLabelText('Nuevo precio (en pesos)'), '200000');
    fireEvent.change(within(panel).getByLabelText('Aplica desde'), {
      target: { value: '2026-10-01' },
    });
    await user.click(within(panel).getByRole('button', { name: 'Programar precio' }));
    expect(await within(panel).findByRole('alert')).toHaveTextContent(
      new RegExp(String.raw`puede empezar desde el ${OCT_26}`),
    );
    expect(billingClient.setPlanPrice).not.toHaveBeenCalled();

    fireEvent.change(within(panel).getByLabelText('Aplica desde'), {
      target: { value: '2026-11-01' },
    });
    await user.click(within(panel).getByRole('button', { name: 'Programar precio' }));
    const dialog = await screen.findByRole('alertdialog', {
      name: '¿Cambiar el precio de Iniciación?',
    });
    expect(within(dialog).getByText(/Avisaremos hoy a 12 jugadores/)).toBeInTheDocument();
    await user.click(within(dialog).getByRole('button', { name: 'Sí, cambiar precio' }));
    await waitFor(() =>
      expect(billingClient.setPlanPrice).toHaveBeenCalledWith('plan-1', {
        basePriceCop: 200000,
        validFrom: '2026-11-01',
      }),
    );
  });

  it('a waiting change can be cancelled', async () => {
    billingClient.listPlans.mockResolvedValue({
      plans: [
        {
          ...INICIACION,
          scheduledPrice: { basePriceCop: 200000, validFrom: '2026-10-26T00:00:00.000Z' },
        },
      ],
    });
    billingClient.cancelScheduledPrice.mockResolvedValue({ currentPriceCop: 180000 });
    const user = userEvent.setup();
    renderPage();
    expect(
      await screen.findByText(new RegExp(String.raw`Pasa a \$\s200\.000 el ${OCT_26}`)),
    ).toBeInTheDocument();
    const panel = await openEditor(user, 'Iniciación');
    expect(within(panel).queryByLabelText('Nuevo precio (en pesos)')).not.toBeInTheDocument();
    await user.click(within(panel).getByRole('button', { name: 'Cancelar cambio programado' }));
    const dialog = await screen.findByRole('alertdialog', {
      name: '¿Cancelar el cambio de precio?',
    });
    await user.click(within(dialog).getByRole('button', { name: 'Sí, cancelar cambio' }));
    await waitFor(() => expect(billingClient.cancelScheduledPrice).toHaveBeenCalledWith('plan-1'));
  });

  it('deactivating asks first and says the current players keep the plan', async () => {
    billingClient.setPlanActive.mockResolvedValue({ ...INICIACION, isActive: false });
    const user = userEvent.setup();
    renderPage();
    const panel = await openEditor(user, 'Iniciación');
    await user.click(within(panel).getByRole('button', { name: 'Desactivar plan' }));
    const dialog = await screen.findByRole('alertdialog', { name: '¿Desactivar Iniciación?' });
    expect(
      within(dialog).getByText(/Los 12 jugadores que ya lo tienen lo conservan/),
    ).toBeInTheDocument();
    await user.click(within(dialog).getByRole('button', { name: 'Sí, desactivar' }));
    await waitFor(() => expect(billingClient.setPlanActive).toHaveBeenCalledWith('plan-1', false));
  });

  it('shows a clear message when the name is already used', async () => {
    billingClient.updatePlan.mockRejectedValue(
      Object.assign(new Error('dup'), { code: 'plan_name_already_exists' }),
    );
    const user = userEvent.setup();
    renderPage();
    const panel = await openEditor(user, 'Iniciación');
    const name = within(panel).getByLabelText('Nombre del plan');
    await user.clear(name);
    await user.type(name, 'Avanzado');
    await user.click(within(panel).getByRole('button', { name: 'Guardar cambios' }));
    expect(
      await within(panel).findByText('Ya existe un plan con ese nombre. Elige otro.'),
    ).toBeInTheDocument();
  });

  it('the notice days are saved from the settings card', async () => {
    billingClient.setPriceNoticeDays.mockResolvedValue({ days: 15 });
    const user = userEvent.setup();
    renderPage();
    await user.type(await screen.findByLabelText('Nuevo aviso (días)'), '15');
    await user.click(screen.getByRole('button', { name: 'Guardar aviso' }));
    await waitFor(() => expect(billingClient.setPriceNoticeDays).toHaveBeenCalledWith(15));
    expect(await screen.findByText('15 días')).toBeInTheDocument();
  });
});
